Table Account{
    id int
    name varchar
    type enum("ASSET", "LIABILITY", "EQUITY", "INCOME", "EXPENSE")
    balance enum("debit","credit")
}

Table Transaction{
    id int [pk]
    date_time date
    total_amount 
    type enum("debit","credit")
}

Table TransactionLine{
    id int [pk]
    transaction_id 
    account_id 
    debit_amount
    credit_amount
}

Table Customer{
    id int 
    name varchar
    phone varchar

}

Table Vendor{
    id int 
    name varchar
    phone varchar
    
}